services:
  gateway:
    build:
      context: ./meddit-gateway
      no_cache: true
    container_name: meddit-gateway
    env_file:
      - .env
    ports:
      - "8000:8000"

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
